### ISSUE TITLE
[Request] Some icons seem to be missing

### ISSUE THREAD

**Issue by sff1019** [fermentationist/devicon-react-svg#1]
Hello, I really love your work, and seems to work great with react+typescript.
One request, some icons seems to be missing (ex: vuejs, typescript, etc)

Will it be possible for you to add them? 

Thank you!

**Comment by fermentationist** [comment]
Hi! Thanks so much for your supportive words! I am very sorry it has taken
me so long to reply. I have just pushed a new version of devicon-react-svg,
and have added the following icons: "typescript", "typescript_badge",
"vuejs", "vuejs_color", "webpack", and "webpack_color". I hope they will be
useful to you!

Regards,

Dennis

**Comment by sff1019** [comment]
Awesome!
Thank you very much!
