### ISSUE TITLE
TypeError: Failed to execute 'getComputedStyle' on 'Window'

### ISSUE THREAD

**Issue by createdbyken** [fermentationist/devicon-react-svg#8]
Hello! I'm having a rough time using this with Next.js
I get this issue:
![Captura de pantalla 2021-01-02 a la(s) 18 21 46](https://user-images.githubusercontent.com/19543206/103469205-65af9080-4d27-11eb-85d5-829c95f99a07.png)

Now, I know that for Next.js SVGS aren't such a thing, so in that case, I'm using next-images in order to solve this problem but I can't actually figure it out that much.

What I'm actually using to read SVG's in **next.config.js**.

```
// next.config.js
const withImages = require('next-images');
module.exports = withImages();
```

My JSX:

```
import DevIcon from 'devicon-react-svg'

const devIconStyleBlk = {
	fill: "black",
	width: "80px",
};

const devIconStyleWht = {
	fill: "white",
	width: "80px",
};

export default function Icons() {
   return (
        <div><DevIcon icon="ruby" style={devIconStyleBlk} viewBox="0 0 32 32" /></div>
        <div><DevIcon icon="python" style={devIconStyleBlk} viewBox="0 0 32 32" /></div>
        <div><DevIcon icon="ror" style={devIconStyleBlk} viewBox="0 0 32 32" /></div>
        <div><DevIcon icon="nodejs_small" style={devIconStyleBlk} viewBox="0 0 32 32" /></div>
        <div><DevIcon icon="postgresql" style={devIconStyleBlk} viewBox="0 0 32 32" /></div>
  )
}
```

Will be much appreciated your support, thanks!

**Comment by fermentationist** [comment]
Sorry Ken, but I don’t have any experience with next. My apologies that it’s not working as expected, but I don’t expect to have time to work on this issue in the immediate future. I am open to accepting a pull request if you think you can solve the issue, however.

Thanks!

**Comment by createdbyken** [comment]
Got it, thanks for your sincerity, I'll open a pull request for this as soon as I can. 
For now, I'm just closing this issue until I'll make my pull request.

Thanks!
